### ISSUE TITLE
Making "INPUT/" default, but optionally variable

### ISSUE THREAD

**Issue by aerorahul** [NOAA-GFDL/FMS#572] opened 2020-09-03 21:34 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem, but poses a limitation.

**Describe the solution you'd like**
The `INPUT/` directory typically contains initial conditions (`restarts`, etc.) , grid information (e.g. `grid_spec.nc`, etc.) and other files.
The word `INPUT/` is hard-wired pretty much everywhere.
For data assimilation, with multiple outer-loops and various resolutions, to initialize the grid, we rely on `INPUT/grid_spec.nc`. When multiple resolutions are involved, and multiple resolutions (`domain`) has to be initialized, this poses a limitation. 

**Describe alternatives you've considered**
Stage several runtime directories e.g. `resolution1/`, `resolution2/`. Each contains `INPUT/grid_spec.nc` relevant to the resolution `resolutionX`. In the calling code, we `cd` into the appropriate `resolutionX` and call the initialization of the grid.  Note this is only initializing the grid structure.

Anticipated changes are limited to the following files:
```
fms/fms_io.F90
fms2_io/fms_netcdf_domain_io.F90
mosaic/mosaic2.F90
mosaic/mosaic.F90
mosaic/grid.F90
```

Optionally, hard-wired `INPUT/` can easily be removed from:
```
interpolator/interpolator.F90
```

Tagging @bensonr for facilitating discussion.

**Comment by thomas-robinson** [comment] 2020-09-14 12:08
@aerorahul Is this involved with using nests?  Is that why there are multiple resolutions?

Am I understanding correctly that the problem is that you have nests with different resolutions, so you need multiple `grid_spec.nc` files?

In the libFMS code, the string "*res*" generally refers to "*restart*".  Most restart files have the string "*res*" in their filename.  Using "*res*" for a directory name will only confuse the situation.  We need to think of something more unique.

**Comment by bensonr** [comment] 2020-09-14 13:00
Data assimilation has requirements to use datasets that may be on different grids and requiring them all grids to reside in the INPUT directory will not work if they are mosaics as the various grid_specs will collide. This is something we need to fix along with forcing the grid_spec name by default. The grid_spec file contains information about directories, but it is ignored on favor of the hard-coded INPUT.

Please assign this to @bensonr.

**Comment by aerorahul** [comment] 2020-09-14 13:44
> @aerorahul Is this involved with using nests? Is that why there are multiple resolutions?
> 
> Am I understanding correctly that the problem is that you have nests with different resolutions, so you need multiple `grid_spec.nc` files?
> 
> In the libFMS code, the string "_res_" generally refers to "_restart_". Most restart files have the string "_res_" in their filename. Using "_res_" for a directory name will only confuse the situation. We need to think of something more unique.

@thomas-robinson 
Thanks for asking to clarify.  `res` in the description pertains to `resolution` and not `restart`.  I have updated the description to clear any confusion with regards to that.

This does not involve the use of nests, but then I am not familiar with how nests are involved in this.

**Comment by aerorahul** [comment] 2020-09-14 15:23
@thomas-robinson @bensonr 
I have made a few initial changes and will point you to a branch shortly.  If it suits you, maybe we can discuss the changes and the context.

**Closed** 2022-03-03 17:55 UTC
Labels: enhancement
