### ISSUE TITLE
FMS 2020.03-alpha1 cause crashes in diag_manager_end with NetCDF: Numeric conversion not representable

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#447] opened 2020-06-06 03:03 UTC
**Describe the bug**
Restart regression tests of two different models crash in diag_manager_end in the second leg of experiemnt with the following traceback: 

```
FATAL from PE  1728: NetCDF: Numeric conversion not representable

Image              PC                Routine            Line        Source
fms_esm4.1_sis2_c  00000000053606F6  Unknown               Unknown  Unknown
fms_esm4.1_sis2_c  000000000337C913  mpp_mod_mp_mpp_er          68  mpp_util_mpi.inc
fms_esm4.1_sis2_c  00000000031145D0  fms_io_utils_mod_         164  fms_io_utils.F90
fms_esm4.1_sis2_c  00000000030B872B  netcdf_io_mod_mp_         284  netcdf_io.F90
fms_esm4.1_sis2_c  00000000034A69CA  fms_netcdf_domain         834  domain_write.inc
fms_esm4.1_sis2_c  000000000348619F  diag_output_mod_m        1270  diag_output.F90
fms_esm4.1_sis2_c  0000000003195648  diag_util_mod_mp_        2538  diag_util.F90
fms_esm4.1_sis2_c  0000000003461CF0  diag_manager_mod_        3542  diag_manager.F90
fms_esm4.1_sis2_c  000000000345F402  diag_manager_mod_        3760  diag_manager.F90
fms_esm4.1_sis2_c  0000000000416906  coupler_main_IP_c        1995  coupler_main.F90
fms_esm4.1_sis2_c  000000000040CD9D  MAIN__                   1151  coupler_main.F90
```

**To Reproduce**
```
git clone -b RTS https://gitlab.gfdl.noaa.gov/mdt/xml mdt_xml_FMS2020.03
cd mdt_xml_FMS2020.03
fremake -x OM4_COBALT_postxanadu.xml -p ncrc4.intel18 -t prod MOM6_SIS2_compile
frerun -x OM4_COBALT_postxanadu.xml -p ncrc4.intel18 -t prod OM4p5_CORE2_IAF_COBALT_abio_csf_mle200 -r rts --no-transfer -u -s
```

**Expected behavior**
RTS should not crash!

**System Environment**
gaea and orion

**Additional context**
On gaea I see this only if the test has a restart in the middle, but on orion it happens on 1 segment  runs too. Also, I see this only in tests using a ocean mask_table, so this might be @ngs333 old friend issue #409  back in a new suit. 

ESM4 crashes on gaea:
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.03-alpha1min_mom6_ESM4_v1.0.3min_1/ESM4_piControl_D/ncrc4.intel18-prod-openmp/stdout/run/ESM4_piControl_D_2x0m15d_1728x4a_1437x1o.o268648259
```
OM4 crashes on gaea:
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.03-alpha1_mom6_ESM4_v1.0.3_min_0604_1/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc4.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_2x0m15d_1057x1o.o268647635
```
OM4 crashes on orion:
```
OK
/work/noaa/gfdlscr/nzadeh/FMS2020.03-alpha1_mom6_ESM4_v1.0.3_min/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/orion.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_442x1o.o73362 

Crash
/work/noaa/gfdlscr/nzadeh/FMS2020.03-alpha1_mom6_ESM4_v1.0.3_min/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/orion.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_442x1o6.o73533
```

**Comment by uramirez8707** [comment] 2020-06-08 14:11
@nikizadehgfdl Did this run with 2020.02?

**Comment by nikizadehgfdl** [comment] 2020-06-08 14:32
Yes, these tests ran with 2020.02 , the regional diagnostics had a problem  which I believe is now fixed.

**Comment by ngs333** [comment] 2020-06-08 15:43
It seems it may not be too hard to get useful info from the debugger when the crash happens. 
It seems , according to the info Niki has above,  mpp_error_basic () (in file mpp_util_mpi.inc)  is executed during the crash(). As going through this function should be unique to a crash,  breakpoints can be placed in this function and the code be allowed to run (in debugger) till the breakpoint (and crash process) is reached. In the debugger this should provide lots of info.

**Comment by thomas-robinson** [comment] 2020-06-08 17:02
Do you know which diagnostic is causing the issue?

**Comment by nikizadehgfdl** [comment] 2020-06-08 17:17
I just confirmed that the modified regression test with empty diag_table pass. 
So this is not a "restart" issue but I don't understand why it only happens on the 2nd leg of restart tests on gaea.

I am going to add all diagnostics except the regional ones and report back.

**Comment by nikizadehgfdl** [comment] 2020-06-09 13:37
The good news (for @ngs333 at least) is that  the crash happens even without any regional diagnostics in diag_table.

**Comment by nikizadehgfdl** [comment] 2020-06-09 18:57
I ran this in debug mode on orion and got a crash (no FATAL message) with the following traceback
```
forrtl: error (72): floating overflow
Image              PC                Routine            Line        Source
libnetcdff.so.7.0  00002B48B42EBACC  netcdf_mp_nf90_pu     Unknown  Unknown
fms_MOM6_SIS2_com  00000000060A52A3  netcdf_io_mod_mp_         369  netcdf_write_data.inc
fms_MOM6_SIS2_com  000000000618B320  fms_netcdf_domain         834  domain_write.inc
fms_MOM6_SIS2_com  00000000065EBDE0  diag_output_mod_m        1270  diag_output.F90
fms_MOM6_SIS2_com  00000000065454D6  diag_util_mod_mp_        2538  diag_util.F90
fms_MOM6_SIS2_com  000000000522F70D  diag_manager_mod_        3535  diag_manager.F90
fms_MOM6_SIS2_com  000000000523DA77  diag_manager_mod_        3762  diag_manager.F90
fms_MOM6_SIS2_com  000000000523ADAD  diag_manager_mod_        3698  diag_manager.F90
fms_MOM6_SIS2_com  00000000004295EC  coupler_main_IP_c        1995  coupler_main.F90
fms_MOM6_SIS2_com  0000000000416BF4  MAIN__                   1151  coupler_main.F90

```

**Comment by ngs333** [comment] 2020-06-12 00:40
The issue is probably resolved. Merged code changes referenced in #458 and application does not crash anymore. Hope nikizadehgfdl  can further test.

**Comment by ngs333** [comment] 2020-06-19 22:46
Consider writing a version of diag_data_out that is field independent (that does not take field as an argument.) This would be called from inside the first loop (for each file) but outside (before) the second loop. Functionality common to both diag_data_out may be abstracted.

**Comment by ngs333** [comment] 2020-06-24 18:19
Today I added a comment to issue WIP - initialize buffers to zero #458. This comment suggest how we should proceed in resolving the issue.

**Comment by ngs333** [comment] 2020-07-02 16:43
This tested with the changes in issue 496 (https://github.com/NOAA-GFDL/FMS/pull/496 ). 
All tests passes and further details and comments are in issue 496.

**Closed** 2020-07-14 17:38 UTC
Labels: bug
