### ISSUE TITLE
FMS-fregrid consolidation I: remove mosaic directory  

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/FMS#1618] opened 2024-12-03 15:54 UTC
**Is your feature request related to a problem? Please describe.**
In FMS, the `mosaic` directory contains C files that were brought over from `FRE-NCTools`.  Many of the functions defined in these C files are unused or are obsolete.  In addition, these functions are used by `mosaic2_mod` and `horiz_interp_mod` and provide more than just mosaic-related support.  The directory name is thus misleading.

**Describe the solution you'd like**
1. Clean up the C files 
2. Rename the mosaic directory to a more fitting name such as grid_utils (TBD)
3. Update the C functions with current versions from FRE-NCTools

**Describe alternatives you've considered**
Leave as is.

**Additional context**
This change is part of `FMSgridtools` development where `create_xgrid` functions from `FRE-NCTools/fregrid` will be relocated to FMS and `horiz_interp_mod` will become the sole regridding tool supported by MSD

**Comment by rem1776** [comment] 2024-12-03 17:47
@mlee03 I think this is basically a duplicate of #1344, so we should probably close one of them. Which one to close is up to you.

**Closed** 2024-12-19 15:44 UTC
Labels: enhancement
